[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8888  # Netlify dev порт
  targetPort = 5173  # Порт вашого додатку

[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"